theme: jekyll-theme-cayman
# Site settings
title: You Blog                     #你博客的标题
SEOTitle: 你的博客 | You Blog        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: You@gmail.com    
description: "You Blog"              #网站介绍
keyword: "keywords" #关键词
url: "https://username.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: ""  #人生格言
sidebar-avatar:xxx.JPG      # 你的个人头像
# SNS settings
RSS: false
weibo_username:     username
zhihu_username:     username
github_username:    username
facebook_username:  username
jianshu_username:   jianshu_id
friends: [
    {
        title: "简书",
        href: "http://www.jianshu.com/u/jianshu_id"
    }
]
